name: Build macOS binary

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install SHC
      run: brew install shc
    - name: Create executable
      run: shc -f  client_assume_role.sh -o car_mac
    - name: Create executable
      run: shc -f  configure_engine_api.sh -o eac_mac
    - name: Commit executable
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Add latest macOS executable"
        git push
